name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t szidzse/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true szidzse/react-test-up npm test

      - run: docker build -t szidzse/multi-client-up ./client
      - run: docker build -t szidzse/multi-nginx-up ./nginx
      - run: docker build -t szidzse/multi-server-up ./server
      - run: docker build -t szidzse/multi-worker-up ./worker

      - run: docker push szidzse/multi-client-up
      - run: docker push szidzse/multi-nginx-up
      - run: docker push szidzse/multi-server-up
      - run: docker push szidzse/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-555458747175
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip